### ISSUE TITLE
NoMethodError: undefined method `root=' for ActiveModel::Serializer:Class

### ISSUE THREAD

**Issue by agoodno** [rails-api/active_model_serializers#673]
In config/initializers/active_model_serializers.rb:

    ActiveModel::Serializer.root = false
    ActiveModel::ArraySerializer.root = false

Working Gemfile contains:

    gem 'active_model_serializers', github: 'rails-api/active_model_serializers', ref: 'e185becd5d007da2f951d1f88c8872a2deb929e5'

Changed Gemfile to use HEAD:

    gem 'active_model_serializers', github: 'rails-api/active_model_serializers'

Any ideas why I now get this error when running 'rake test'?
```bash
rake aborted!
NoMethodError: undefined method `root=' for ActiveModel::Serializer:Class
~/.rvm/gems/ruby-2.1.1@project1/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:258:in `method_missing'
~/src/project1/config/initializers/active_model_serializers.rb:2:in `<top (required)>'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `block in load'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/engine.rb:648:in `block in load_config_initializer'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/notifications.rb:161:in `instrument'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/engine.rb:647:in `load_config_initializer'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/engine.rb:611:in `each'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/engine.rb:611:in `block in <class:Engine>'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `instance_exec'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `run'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/initializable.rb:54:in `run_initializers'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/application.rb:300:in `initialize!'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `public_send'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `method_missing'
~/src/project1/config/environment.rb:5:in `<top (required)>'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/src/project1/test/test_helper.rb:2:in `<top (required)>'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/src/project1/test/models/account_task_test.rb:17:in `<top (required)>'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
~/.rvm/gems/ruby-2.1.1@project1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:114:in `each'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:113:in `each'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
~/.rvm/gems/ruby-2.1.1@project1/gems/railties-4.1.5/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
~/.rvm/gems/ruby-2.1.1@project1/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.1.1@project1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test:run => test:units
(See full trace by running task with --trace)
```

**Comment by JustinAiken** [comment]
> Yes, root has not been implemented on master yet. You probably want 0.9-stable.

@steveklabnik 

This still seems to be the case on 0.10.0rc1 - should `ActiveModel::Serializer.root = true` work on the .10 branch, or is that option deprecated?

**Comment by macfanatic** [comment]
Looks like this isn't suppported yet on `0.10.0.rc2` either.

**Comment by joaomdmoura** [comment]
@macfanatic It is, but the way it's implemented is different :smile: 

The 0.10.x uses an adapter pattern. If you check the [Adapters section](https://github.com/rails-api/active_model_serializers#built-in-adapters) on README you will see that we implemented 3 different Adapters, ```JSON```, ```JSON API``` and ```Flatten JSON```.

It was implemented a couple weeks ago at the [PR](https://github.com/rails-api/active_model_serializers/pull/958).

Now you can use the usual adapter configuration to determinate with you want to have a root or not:
```ruby
# Without root, the default
ActiveModel::Serializer.config.adapter = :flatten_json

# With root
ActiveModel::Serializer.config.adapter = :json

# Following JSON API conventions
ActiveModel::Serializer.config.adapter = :json_api
````

**Comment by macfanatic** [comment]
Thanks @joaomdmoura I'll give that a try when I attempt to upgrade again.  I had attempted to set the adapter to `flatten_json` and appeared that worked for my arrays, but was still getting `object: {}` root keys throughout any other items and just gave up.

**Comment by joaomdmoura** [comment]
@macfanatic sorry to hear that! Yeah, you should give it a try again! Way easier and stable :smile: 
In case you have some problem just show up at the IRC channel, post it on StackOverflow or on Github and let us know :)

**Comment by wxianfeng** [comment]
hmmm..
i use active_model_serializers 0.10.rc3, and use  flatten_json adapter
response json has root, how to solve it?
i dont want root.

**Comment by bf4** [comment]
@wxianfeng Please open a new issue and take a look at https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md

**Comment by bf4** [comment]
This issue has started to attract off-topic comments. If this is still a problem, please open a new issue, reference which 0.9 version is is for (per https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md )  and reference this issue
